spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  application:
    name:
      EventScope
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8082